version: 0.1.10.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
only_commits:
  files:
     - 'src/'
     - 'external/'
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\classicuo
clone_script:
- cmd: >-

    git --version
    
    git clone -q --branch %APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER% && cd %APPVEYOR_BUILD_FOLDER% && git checkout -qf %APPVEYOR_REPO_COMMIT% && git submodule update --init --recursive
    
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-dev'
environment:
  DEV_BUILD: true
build_script:
- cmd: >-
    nuget restore

    dotnet build "%APPVEYOR_BUILD_FOLDER%" -c release -p:IS_DEV_BUILD=true


    xcopy "%APPVEYOR_BUILD_FOLDER%\tools\monokickstart\*.*" "%APPVEYOR_BUILD_FOLDER%\bin\Release" /Y


    7z a ClassicUO-dev-preview-release.zip "%APPVEYOR_BUILD_FOLDER%\bin\Release\*"


    dotnet run --project "%APPVEYOR_BUILD_FOLDER%\tools\ManifestCreator\ManifestCreator.csproj" "%APPVEYOR_BUILD_FOLDER%\bin\Release" "dev-preview" "ClassicUO-dev-preview-release.zip"
artifacts:
- path: ClassicUO-dev-preview-release.zip
  name: ClassicUO
- path: manifest.xml
  name: manifest
deploy:
#- provider: GitHub
#  tag: ClassicUO-dev-preview
#  release: ClassicUO-dev-preview
#  description: 'Appveyor autodeploy.\nThis build may not be safe: use it at your own risk.\nIt does not contain Razor.'
#  auth_token:
#    secure: sFMPr0POE5r5CFP5XbTD0e5pZVRO/12A3LgkqKVDD2uB2Webo6gstCTm63KzcbaW
#  artifact: ClassicUO-dev-preview-release.zip
#  draft: false
#  prerelease: true
#  force_update: true
#  on:
#    branch: dev
- provider: FTP
  host: ftp.classicuo.eu
  protocol: ftp
  username:
    secure: JaSH/LFfqcrUBZ5USwkYozDFFZUmyRZJyxsB/LSNOlI=
  password:
    secure: LxmPxo+VaKeJQxV1jqH6eecs4Mid+RaQQsG0JETnMbU=
  folder: /www.classicuo.eu/dev/deploy
  artifact: ClassicUO-dev-preview-release.zip, manifest
  active_mode: false
  beta: false
  debug: false
  on:
    branch: dev
