name: Build-Release

on:
  workflow_dispatch:
  push:
    branches: "dev"
    paths:
      - 'src/**/*'
      - 'external/**/*'


env:
  CUO_ASSEMBLY_VERSION: '0.1.10.${{ github.run_number }}'
  CUO_OUTPUT_PATH: 'bin/dist'
  CUO_PROJECT_PATH: "src/ClassicUO.csproj"

  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ windows-latest ]

    steps:
    - uses: actions/checkout@v2
      
    - name: Get submodules
      run: git submodule update --init --recursive
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
            
    - name: Build
      run: dotnet publish ${{ env.CUO_PROJECT_PATH }} -c Release -o ${{ env.CUO_OUTPUT_PATH }} -p:IS_DEV_BUILD=true -p:AssemblyVersion=${{ env.CUO_ASSEMBLY_VERSION }} -p:FileVersion=${{ env.CUO_ASSEMBLY_VERSION }}
      
    - name: Create package
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{ env.CUO_OUTPUT_PATH }}
        filename: 'ClassicUO-dev-release.zip'
        exclusions: 'ClassicUO.exe.config'
        
    - name: Remove old Release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: ClassicUO-dev-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.CUO_OUTPUT_PATH }}/ClassicUO-dev-release.zip"
        name: 'ClassicUO dev preview'
        body: 'This build may not be safe: use it at your own risk.'
        prerelease: true
        tag: ClassicUO-dev-release
        token: ${{ secrets.GITHUB_TOKEN }}
        
